language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo rm /etc/apt/sources.list
  - echo 'deb http://http.debian.net/debian/ jessie main' | sudo dd of=/etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get --force-yes -y install debian-archive-keyring
  - sudo apt-get update
  - sudo dpkg -r --force-depends locales libc6-dev
  - sudo apt-get -f install
  - make
install:
  - "pip install requests"
script:
  - cd sandcats ; python trivial_tests.py
