language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  # Remove some packages that actively depend on locales working properly.
  - sudo apt-get remove postgresql-9.1 postgresql-contrib-9.1 postgresql-9.2 postgresql-contrib-9.2 postgresql-9.3 postgresql-contrib-9.3 postgresql-9.4 postgresql-contrib-9.4
  # Remove some packages that we get from Debian anyway.
  - sudo apt-get remove --purge -y mongodb-10gen
  # Tell dpkg it is OK to choose the new config files, without prompting.
  - echo 'Dpkg::Options { "--force-confdef"; "--force-confnew"; }' | sudo dd of=/etc/apt/apt.conf.d/99conf
  # Trans-grade to Debian.
  - sudo rm /etc/apt/sources.list
  - echo 'deb http://http.debian.net/debian/ jessie main' | sudo dd of=/etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get --force-yes -y install debian-archive-keyring
  - sudo apt-get update
  - sudo rm -f /etc/dpkg/dpkg.cfg.d/multiarch  # Remove historic multi-arch config.
  - echo -n | sudo dd of=/var/lib/dpkg/info/libc-bin.list  # Pretend nothing conflicts with this package's files.
  - sudo dpkg -r --force-depends --force-remove-essential locales libc6-dev
  - sudo apt-get --fix-broken install
  # Make sure locales are in a healthy shape.
  - echo 'en_US.UTF-8 UTF-8' | sudo dd of=/etc/locale.gen
  - sudo /usr/sbin/locale-gen
  # Remove udev, and let us get the Debian version.
  - sudo dpkg --purge --force-depends udev initramfs-tools
  - sudo apt-get --fix-broken install
  # Do the Sandcats installing.
  - make stage-provision
  # Now, ask systemd to take over PID 1.
  - echo | sudo gdb -p 1 --eval-command='call execl(strdup("/lib/systemd/systemd"), strdup("systemd"), 0, 0)'
  - sleep 10
  - sudo tail -n 200 /var/log/syslog
install:
  - sudo apt-get install python-requests
script:
  - cd sandcats ; python trivial_tests.py
